import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nav from "@/components/navbar/Nav";
import Footer from "@/components/footer/Footer";
import { AuthProvider } from "@/context/AuthContext";
import ExcludedWrapped from "@/components/navbar/ExcludedWrapped";
import { CartProvider } from "@/context/CartContext";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <AuthProvider>
          <CartProvider>
            <ExcludedWrapped>
              <Nav />
            </ExcludedWrapped>
                  <main>{children}</main>
            <ExcludedWrapped>
            <Footer />
            </ExcludedWrapped>
          </CartProvider>
        </AuthProvider>


      </body>
    </html>
  );
}
